### Mensaje Bienvenida del server
GET  http://localhost:3977

### Obtenemos un token
POST http://localhost:3977/api/v1/sign-in
Content-Type: application/json

{
    "email" : "740390@unizar.es",
    "password" : "123456789"
}

### Creamos Inquilino
POST http://localhost:3977/api/v1/inmueble
Content-Type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzYjVmY2JhNTE1NzVhYTNkNTI2NDZiMCIsIm5hbWUiOiJKb3NlMyIsImxhc3RuYW1lIjoiUGVkcm8iLCJlbWFpbCI6Ijc0MDM5MEB1bml6YXIuZXMiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVUb2tlbiI6MTY3NDAwMjAzNiwiZXhwIjoxNjc0MDA1NjM2fQ.MPpgezaMUoYL6bKJ5kr7pQk2tKYcR-6MiLebDvQyvp8

{
  "name": "Casa Montse",
  "owner": "Montse",
  "shelly_abrir_puerta_ID": "e89f6d860023",
  "shelly_temperatura_ID": "e89f6d860023",
  "shelly_potencia_ID": "e89f6d860023"
}

###
GET http://localhost:3977/api/v1/inmuebles
Content-Type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzYjVmY2JhNTE1NzVhYTNkNTI2NDZiMCIsIm5hbWUiOiJKb3NlMyIsImxhc3RuYW1lIjoiUGVkcm8iLCJlbWFpbCI6Ijc0MDM5MEB1bml6YXIuZXMiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVUb2tlbiI6MTY3NDAwMjAzNiwiZXhwIjoxNjc0MDA1NjM2fQ.MPpgezaMUoYL6bKJ5kr7pQk2tKYcR-6MiLebDvQyvp8

{}

###
DELETE http://localhost:3977/api/v1/inmueble/63c73fd7354db0a1ee4140aa
Content-Type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzYjVmY2JhNTE1NzVhYTNkNTI2NDZiMCIsIm5hbWUiOiJKb3NlMyIsImxhc3RuYW1lIjoiUGVkcm8iLCJlbWFpbCI6Ijc0MDM5MEB1bml6YXIuZXMiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVUb2tlbiI6MTY3NDAwMjAzNiwiZXhwIjoxNjc0MDA1NjM2fQ.MPpgezaMUoYL6bKJ5kr7pQk2tKYcR-6MiLebDvQyvp8

{}
### Actualizamos Inquilino
PATCH  http://localhost:3977/api/v1/inmueble/63c73f4a5033a0ca100491de
Content-Type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzYjVmY2JhNTE1NzVhYTNkNTI2NDZiMCIsIm5hbWUiOiJKb3NlMyIsImxhc3RuYW1lIjoiUGVkcm8iLCJlbWFpbCI6Ijc0MDM5MEB1bml6YXIuZXMiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVUb2tlbiI6MTY3NDAwMjAzNiwiZXhwIjoxNjc0MDA1NjM2fQ.MPpgezaMUoYL6bKJ5kr7pQk2tKYcR-6MiLebDvQyvp8

{
  "name": "Casa Montse",
  "owner": "Montse",
  "shelly_abrir_puerta_ID": "e89f6d860023",
   "shelly_temperatura_ID": "34945471e023",
  "shelly_potencia_ID": "e89f6d860023"
}


### Obtenemos temperatura Inmueble
GET  http://localhost:3977/api/v1/inmueble/8d5a91f6-4e19-49c3-88cf-22dd9c036eaa/temperature
Content-Type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzYjVmY2JhNTE1NzVhYTNkNTI2NDZiMCIsIm5hbWUiOiJKb3NlMyIsImxhc3RuYW1lIjoiUGVkcm8iLCJlbWFpbCI6Ijc0MDM5MEB1bml6YXIuZXMiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVUb2tlbiI6MTY3NDAwMjAzNiwiZXhwIjoxNjc0MDA1NjM2fQ.MPpgezaMUoYL6bKJ5kr7pQk2tKYcR-6MiLebDvQyvp8

{
}
